routes/web.php
<?php

use App\Http\Controllers\Admin\AdminErrorPageController;
use App\Http\Controllers\Admin\GameController;
use App\Http\Controllers\Admin\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('admin.dashboard');
});
// Route::get('/admin', function () {
//     return redirect('/admin/dashboard');
// });
Auth::routes(['register' => false]);
// Route::get('/test', 'TestController@test');
// Route::controller(TestController::class)->group(function () {
//     //
// });
Route::get('/admin/test', 'TestController@test');



Route::group(['middleware' => ['optimizeImages'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', function () {
        return redirect()->route('admin.dashboard');
    });

    Route::controller(LoginController::class)->group(function () {
        Route::get('/login', 'showLoginForm')->name('login');
        Route::post('/login', 'login')->name('login');
        Route::post('/logout', 'logout')->name('logout');
    });
    Route::controller(AdminErrorPageController::class)->group(function () {
        Route::get('/404', 'pageNotFound')->name('notfound');
        Route::get('/500', 'serverError')->name('server_error');
    });
    Route::group(['middleware' => ['auth'], 'namespace' => 'Admin'], function () {

        Route::controller(DashboardController::class)->group(function () {
            Route::get('/test', 'test')->name('test');
            Route::get('/dashboard', 'index')->name('dashboard');
            Route::get('dashboard-counts', 'dashboardCountsData')->name('dashboard-counts');
        });

        Route::controller(AdminProfileController::class)->group(function () {
            Route::get('/profile', 'profile')->name('profile');
            Route::get('change-password', 'changePassword')->name('change_password');
            Route::put('change-password/{user}', 'updatePassword')->name('update.password');
        });

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        // // Route::resource('/apilogin', CAuthController::class);
        // Route::controller(CAuthController::class)->group(function () {
        //     Route::post('/login', 'login')->name('login');
        // });

        Route::controller(UserController::class)->group(function () {
            Route::get('/update_language/{user}/{language}', 'updateLanguage')->name('users.update_language');
            Route::get('/users/status/{id}/{status}', 'status')->name('users.status');
            Route::post('/users/download', 'export')->name('users.download');
        });
        Route::resource('/users', UserController::class);

        Route::controller(BattleController::class)->group(function () {
            Route::get('/battles/status/{id}/{status}', 'status')->name('battles.status');
        });
        Route::resource('/battles', BattleController::class);

        Route::controller(WinningController::class)->group(function () {
            Route::get('/winnings/status/{id}/{status}', 'status')->name('winnings.status');
        });
        Route::resource('/winnings', WinningController::class);

        Route::controller(GameController::class)->group(function () {
            Route::get('/games/status/{id}/{status}', 'status')->name('games.status');
            // Route::post('/games/store', 'store')->name('games.store');
        });
        Route::resource('/game', GameController::class);

        Route::controller(ResultController::class)->group(function () {
            Route::get('/results/status/{id}/{status}', 'status')->name('results.status');
            // Route::post('/games/store', 'store')->name('games.store');
            Route::get('/result/approve/{id}/{status}', 'approve')->name('result.approve');
        });
        Route::resource('/result', ResultController::class);

        Route::controller(GameResultController::class)->group(function () {
            Route::get('/gameresults/status/{id}/{status}', 'status')->name('gameresults.status');
            // Route::post('/games/store', 'store')->name('games.store');
        });
        Route::resource('/gameresult', GameResultController::class);


        Route::controller(WalletHistoryController::class)->group(function () {
            Route::get('/wallethistorys/status/{id}/{status}', 'status')->name('wallethistorys.status');
            // Route::post('/games/store', 'store')->name('games.store');
        });

        Route::resource('/wallethistory', WalletHistoryController::class);

        Route::controller(ExcelController::class)->group(function () {
            Route::get('/excels/status/{id}/{status}', 'status')->name('excels.status');
         
        });
        Route::resource('/excel', ExcelController::class);



        Route::controller(CustomerController::class)->group(function () {
            Route::get('/customers/status/{id}/{status}', 'status')->name('customers.status');
            Route::post('/customers/download', 'export')->name('customers.download');
            Route::get('/customers/download', 'export')->name('customers.getdownload');
        });
        Route::resource('/customers', CustomerController::class);

        Route::controller(ProductController::class)->group(function () {
            Route::get('/products/status/{id}/{status}', 'status')->name('products.status');
            Route::post('/products/download', 'export')->name('products.download');
            Route::get('/products/download', 'export')->name('products.getdownload');
            Route::post('/products/import', 'import')->name('products.import');
            Route::get('products/get-format-files', 'downloadImportFormatFile')->name('products.getfile');
            Route::delete('products/delete-images/{id}', 'deleteImage')->name('products.delete_image');
        });
        Route::resource('/products', ProductController::class);

        //Setting manager
        Route::controller(SettingController::class)->group(function () {
            Route::get('/settings/general', 'edit_general')->name('settings.edit_general');
            Route::post('/settings/general', 'update_general')->name('settings.update_general');
        });
    });
});

app/Models/Excel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Excel extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = [

        // 'battle_id',
        'excel_file',
        // 'room_code'
        // 'no_battle',
        // 'entry_amount',
        // 'win_amount',
        // 'trending_game'
    ];

}

app/Http/Controllers/Admin/ExcelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ExcelRequest;
use App\Models\Game;
use App\Services\ExcelService;
use App\Services\CustomerService;
use App\Services\ManagerLanguageService;
use App\Services\UserService;
use App\Services\UtilityService;
use Illuminate\Http\Request;

class ExcelController extends Controller
{
    protected $mls, $change_password, $assign_role, $uploads_image_directory;
    protected $index_view, $create_view, $edit_view,$excel_view, $detail_view, $tabe_view, $product_history_view;
    protected $index_route_name, $create_route_name, $detail_route_name, $edit_route_name,$excel_route_name;
    protected $excelService, $utilityService, $customerService;

    public function __construct()
    {
        //Permissions
        // $this->middleware('permission:battle-list|battle-create|battle-edit|battle-delete', ['only' => ['index', 'store']]);
        // $this->middleware('permission:battle-create', ['only' => ['create', 'store']]);
        // $this->middleware('permission:battle-edit', ['only' => ['edit', 'update', 'status']]);
        // $this->middleware('permission:battle-delete', ['only' => ['destroy']]);

        //Data
        $this->uploads_image_directory = 'files/game';
        //route
        $this->index_route_name = 'admin.excel.index';
        $this->create_route_name = 'admin.excel.create';
        $this->excel_route_name = 'admin.excel.excel';
        // $this->detail_route_name = 'admin.game.show';
        $this->edit_route_name = 'admin.excel.edit';
        // $this->excel_form_route_name = 'admin.game.excel_form';

        //view files
        // $this->index_view = 'admin.excel.index';
        $this->create_view = 'admin.excel.create';
        // $this->excel_view = 'admin.excel.excel';
        $this->detail_view = 'admin.excel.details';
        $this->tabe_view = 'admin.excel.profile';
        $this->edit_view = 'admin.excel.edit';
        // $this->excel_form_view = 'admin.game.excel_form';
        
        $this->product_history_view = 'admin.excel.product_history';
        $this->change_password = 'admin.admin_profile.change_password';

        //service files
        $this->excelService = new ExcelService();
        $this->customerService = new CustomerService();
        $this->utilityService = new UtilityService();

        //mls is used for manage language content based on keys in messages.php
        $this->mls = new ManagerLanguageService('messages');
    }

   

    public function create()
    {
        // echo"Hello";
        // die;
        return view($this->create_view);
    }
        public function store(ExcelRequest $request)
    {
       
        $input = $request->except(['_token', 'proengsoft_jsvalidation']);
        // print_r($input);
        // die;
        $logo=$request->file('excel_file');

        $filename    = time().$logo->getClientOriginalName();
        $destinationPath = public_path('/files/game/');

        $logo->move($destinationPath, $filename);
        $input['excel_file']=$filename;
        $excel = $this->excelService->create($input);

        return redirect()->route($this->create_route_name)
            ->with('success', $this->mls->messageLanguage('created', 'excel', 1));

    }
}

resources/views/admin/excel/create.blade.php
@extends('admin.layouts.base')
@section('content')
    @include('admin.layouts.components.header', [
        'title' => __('messages.create', ['name' => trans_choice('content.excel', 1)]),
        'breadcrumbs' => Breadcrumbs::render('admin.excel.create'),
    ])

    <!--begin::Post-->
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container">
            <!--begin::Careers - Apply-->
            <div class="card">
                <!--begin::Body-->
                <div class="card-body">
                    <!--begin::Layout-->
                    <div class="d-flex flex-column flex-lg-row">
                        <!--begin::Content-->
                        <div class="flex-lg-row-fluid me-0 me-lg-20">

                            <!--begin::Form-->
                            {!! Form::open(['route' => 'admin.excel.store', 'method' => 'POST', 'class' => 'form', 'enctype' => 'multipart/form-data']) !!}

                            @include('admin.excel.form')
                            <!--begin::Actions-->
                            <div class="card-footer d-flex justify-content-end py-6 px-9">
                                <a href="{{ route('admin.game.index') }}"
                                    class="btn btn-light btn-active-light-primary me-2 text-black">{{ __('content.back_title') }}</a>
                                <button type="submit" class="btn btn-primary">{{ __('content.create_title') }}</button>
                            </div>
                            <!--end::Actions-->

                            {!! Form::close() !!}
                            <!--end::Form-->
                        </div>
                        <!--end::Content-->
                    </div>
                    <!--end::Layout-->
                </div>
                <!--end::Body-->
            </div>
            <!--end::Careers - Apply-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Post-->
@endsection

resources/views/admin/excel/form.blade.php
<!--begin::Card body-->
<div class="card-body">

    <!--begin::Input group-->
    <div class="row mb-6">
        <!-- <label class="col-lg-2 col-form-label required fw-bold fs-6">Battle Name</label>
        
        <div class="col-lg-4 fv-row">
       
            <input type="text"  class="form-control form-control-lg form-control-solid" name="battle_id" placeholder="Battle Name">
        </div> -->
       
        <label class="col-lg-2 col-form-label required fw-bold fs-6">File</label>
        <!--end::Label-->
        <!--begin::Col-->
        <div class="col-lg-4 fv-row">
            <!-- {!! Form::text('room_no', null, ['placeholder' => trans_choice('content.room_no_title', 1), 'value' => 'Max', 'class' => 'form-control form-control-lg form-control-solid mb-3 mb-lg-0']) !!} -->
            <input type="file" class="form-control form-control-lg form-control-solid" name="excel_file">
        </div>

        
        <!--end::Col-->
    </div>
    <div class="row mb-6">

        <!-- <label class="col-lg-2 col-form-label fw-bold fs-6">
            <span class="required">Room Code</span>
            
        </label> -->
        <!--end::Label-->
        <!--begin::Col-->
        <!-- <div class="col-lg-4 fv-row">
            -->
        <!-- {!! Form::number('prize', null, ['placeholder' => trans_choice('content.prize_title', 1), 'class' => 'form-control form-control-lg form-control-solid']) !!} -->
        <!-- <input type="number" name="room_code" class="form-control form-control-lg form-control-solid" placeholder="Room code">  
        </div> -->
        <!--end::Col-->
    </div>
    <!--end::Input group-->

    <!--begin::Input group-->
    
    <!--end::Input group-->

    <!--begin::Input group-->

    <!--end::Input group-->
   

</div>
<!--end::Card body-->

@push('scripts')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js') }}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\Admin\winningRequest', 'form') !!}
@endpush

resources/views/admin/excel/index.blade.php
@extends('admin.layouts.base')

{{-- @section('admin_filter_form')
    {!! Form::open(['route' => 'admin.excels.download', 'method' => 'POST', 'id' => 'filter_data', 'class' => 'form mb-15']) !!}
    <!--begin::Card body-->
    
    <div class="card-body">
        <!--begin::Input group-->
        <div class="row mb-6">
            <!--begin::Label-->
            <label
                class="col-lg-4 col-form-label required fw-bold fs-6">{{ trans_choice('content.excels.name', 1) }}</label>
            <!--end::Label-->
            <!--begin::Col-->
            <div class="col-lg-8 fv-row">
                <!-- {!! Form::text('name', null, ['placeholder' => __('content.battles.name'), 'value' => 'Max', 'class' => 'form-control form-control-lg form-control-solid mb-3 mb-lg-0 search_input']) !!} -->
            <input type="text" name="game_name" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0 search_input">
            </div>
            <!--end::Col-->

        </div>
        <!--end::Input group-->

        <!--begin::Input group-->
        <div class="row mb-6">
            <!--begin::Label-->
            <label class="col-lg-4 col-form-label fw-bold fs-6">
                <span class="required">{{ trans_choice('content.excels.id', 1) }}</span>
            </label>
            <!--end::Label-->
            <!--begin::Col-->
            <div class="col-lg-8 fv-row">
                <!-- {!! Form::text('battle_id', null, ['placeholder' => __('placeholder.battle_id'), 'class' => 'form-control form-control-lg form-control-solid only_number search_input']) !!} -->
                <input type="text" name="excel_id" class="form-control form-control-lg form-control-solid only_number search_input" placeholder="excel id">
            </div>
            <!--end::Col-->
        </div>

        
        <!--end::Input group-->

        <!--begin::Input group-->
        <div class="row mb-6">
            <!--begin::Label-->
            <label class="col-lg-4 col-form-label fw-bold fs-6">{{ trans_choice('content.status_title', 1) }}</label>
            <!--end::Label-->
            <!--begin::Input-->
            <div class="col-lg-8 fv-row">
                <select class="form-control form-control-lg form-control-solid search_input" data-control="select2"
                    name="status">
                    <option value="">{{ trans_choice('content.please_select', 1) }}</option>
                    <option value="1">{{ trans_choice('content.active_title', 1) }}</option>
                    <option value="0">{{ trans_choice('content.inactive_title', 1) }}</option>
                </select>
            </div>
            <!--end::Input-->
        </div>
        <!--end::Input group-->
        <!--end::Input group-->
    </div>
    <!--end::Card body-->

    <!--begin::Actions-->
    <div class="d-flex justify-content-end">
        @include('admin.layouts.components.buttons.white_btn', [
            'type' => 'reset',
            'id' => 'searchReset',
            'attr' => 'data-kt-menu-dismiss="true"',
            'title' => trans_choice('content.reset', 1),
            'class' => 'btn-active-light-primary',
        ])
        @include('admin.layouts.components.buttons.primary_btn', [
            'id' => 'extraSearch',
            'attr' => 'data-kt-menu-dismiss="true"',
            'title' => __('content.search_title'),
        ])
        @include('admin.layouts.components.buttons.exportbtn')
    </div>
    <!--end::Actions-->
    {!! Form::close() !!}
@endsection --}}

@section('content')
    @include('admin.layouts.components.header', [
        'title' => __('messages.list', [
            'name' => trans_choice('content.excel', 2),
        ]),
        'breadcrumbs' => Breadcrumbs::render('admin.excel.index'),
        'filter' => false,
        'create_btn' => [
            'status' => true,
            'route' => route('admin.excel.create'),
            'name' => __('messages.create', [
                'name' => trans_choice('content.excel', 1),
            ]),
        ],
        // 'export' => [
        //     'status' => true,
        //     'route' => route('admin.excels.getdownload'),
        // ],
    ])
    @include('admin.layouts.components.datatable_header', [
        'data' => [
            ['classname' => '', 'title' => trans_choice('content.id_title', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.name', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.image', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.no_player', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.no_room', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.entry_amount', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.win_amount', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.trending_game', 1)],
            
            ['classname' => 'min-w-100px', 'title' => trans_choice('content.action_title', 1)],
        ],
    ])
@endsection

@push('scripts')
    <script>
        var oTable;
        $(document).ready(function() {
            oTable = $('#kt_table_1').DataTable({
                responsive: true,
                searchDelay: 500,
                processing: true,
                serverSide: true,
                order: [
                    [0, 'desc']
                ],
                oLanguage: {
                    sLengthMenu: "Show _MENU_",
                },
                createdRow: function(row, data, dataIndex) {
                    // Set the data-status attribute, and add a class
                    $(row).attr('role', 'row');
                    $(row).find("td").last().addClass('text-danger');
                },
                ajax: {
                    "url": "{{ route('admin.excel.index') }}",
                },
             
                columns: [{
                        data: 'id',
                        name: 'id',
                        render: function(data, type, row, meta) {
                            return data;
                            // return "#" + serialNumberShow(meta);
                        }
                    },

                    {
                        data: 'excel_name',
                        name: 'excel_name',
                        render: function(data, type, row, meta) {
                            var show_url = `{{ url('/') }}/admin/excel/` + row['id'] +
                                `?tab=details`;
                            return ` <a href="${show_url}">
                                        <div class="font-medium whitespace-no-wrap">${data}</div>
                                    </a>`;
                        }
                    },
                    {
                        data: 'banner_image',
                        name: 'banner_image',
                        render: function(data, type, row, meta) {
                            return `<div class="font-medium whitespace-no-wrap"><img src="{{url('/') }}/files/excel/${data}" height="50"></div>`;
                        }
                    },
                    {
                        data: 'no_player',
                        name: 'no_player',
                        render: function(data, type, row, meta) {
                            return `<div class="font-medium whitespace-no-wrap">${data}</div>`;
                        }
                    },
                    {
                        data: 'no_battle',
                        name: 'no_battle',
                        render: function(data, type, row, meta) {
                            // return `<div class="font-medium whitespace-no-wrap">getDateTimeByFormat(${data})</div>`;
                            return `<div class="font-medium whitespace-no-wrap">${data}</div>`;
                        }
                    },
                    {
                        data: 'entry_amount',
                        name: 'entry_amount',
                        render: function(data, type, row, meta) {
                            // return `<div class="font-medium whitespace-no-wrap">getDateTimeByFormat(${data})</div>`;
                            return `<div class="font-medium whitespace-no-wrap">${data}</div>`;
                        }
                    },
                    {
                        data: 'win_amount',
                        name: 'win_amount',
                        render: function(data, type, row, meta) {
                            // return `<div class="font-medium whitespace-no-wrap">getDateTimeByFormat(${data})</div>`;
                            return `<div class="font-medium whitespace-no-wrap">${data}</div>`;
                        }
                    },
                    {
                        data: 'trending_game',
                        name: 'trending_game',
                        render: function(data, type, row, meta) {
                            // return `<div class="font-medium whitespace-no-wrap">getDateTimeByFormat(${data})</div>`;
                            return `<div class="font-medium whitespace-no-wrap">${data}</div>`;
                        }
                    },
                   
                    {
                        data: 'id',
                        name: 'excel_id',
                        // visible:false,
                        render: function(data, type, row, meta) {

                            var edit_url = `{{ url('/') }}/admin/excel/` + row['id'] +
                                `/edit/?tab=edit`;
                            var show_url = `{{ url('/') }}/admin/excel/` + row['id'] +
                                `?tab=details`;
                                var form_url = `{{ url('/') }}/admin/excel/` + row['id'] +
                                `/excel/?tab=excel`;

                            var edit_data = actionEditButton(edit_url, row['id']);
                            var show_data = actionShowButton(show_url);
                            var form_data = actionShowNotesButton(form_url,row['id']);
                            var del_data = actionDeleteButton(row['id']);
                            return `<div class="flex justify-left items-center"> ${show_data}  ${edit_data} ${del_data} ${form_data}</div>`;

                            // return `<div class="flex justify-left items-center"> ${button} </div>`;

                        }
                    },
                ],
            });
            // //start: datatables common js file for changing
            // oTable.columns().iterator('column', function(ctx, idx) {
            //     $(oTable.column(idx).header()).append('<span class="sort-icon"/>');
            // });
            //end: datatables common js file for changing
        });

        $(document).on('click', '.clsdelete', function() {
            var id = $(this).attr('data-id');
            var e = $(this).parent().parent();
            var url = `{{ url('/') }}/admin/excel/` + id;
            tableDeleteRow(url, oTable);
        });

        $(document).on('click', '.clsstatus', function() {
            var id = $(this).attr('data-id');
            var status = $(this).attr('data-status');
            var url = `{{ url('/') }}/admin/excel/status/` + id + `/` + status;
            tableChnageStatus(url, oTable);
        });
    </script>

    <script>
        $('#extraSearch').on('click', function() {
            //extraSearch is id of search button....
            oTable.draw();
        });

        $(document).on('click', '#searchReset', function(e) {
            $('#filter_data').trigger("reset");
            e.preventDefault();
            oTable.draw();
        });

        $(document).on('click', '.drawerReset', function(e) {
            $('#filter_data').trigger("reset");
            e.preventDefault();
            oTable.draw();
        });

        $(document).ready(function() {
            $('#filter_data').trigger("reset");
            oTable.draw();
        });

        $(document).on('click', '#search_filter_excel_download', function(e) {
            var export_type = $(this).attr('data-type');
            console.log(export_type);
            $('#export_type').val(export_type);
            $('#filter_data').submit();
        });
    </script>
@endpush