routes/web.php
<?php

use App\Http\Controllers\Admin\AdminErrorPageController;
use App\Http\Controllers\Admin\GameController;
use App\Http\Controllers\Admin\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('admin.dashboard');
});
// Route::get('/admin', function () {
//     return redirect('/admin/dashboard');
// });
Auth::routes(['register' => false]);
// Route::get('/test', 'TestController@test');
// Route::controller(TestController::class)->group(function () {
//     //
// });
Route::get('/admin/test', 'TestController@test');



Route::group(['middleware' => ['optimizeImages'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', function () {
        return redirect()->route('admin.dashboard');
    });

    Route::controller(LoginController::class)->group(function () {
        Route::get('/login', 'showLoginForm')->name('login');
        Route::post('/login', 'login')->name('login');
        Route::post('/logout', 'logout')->name('logout');
    });
    Route::controller(AdminErrorPageController::class)->group(function () {
        Route::get('/404', 'pageNotFound')->name('notfound');
        Route::get('/500', 'serverError')->name('server_error');
    });
    Route::group(['middleware' => ['auth'], 'namespace' => 'Admin'], function () {

        Route::controller(DashboardController::class)->group(function () {
            Route::get('/test', 'test')->name('test');
            Route::get('/dashboard', 'index')->name('dashboard');
            Route::get('dashboard-counts', 'dashboardCountsData')->name('dashboard-counts');
        });

        Route::controller(AdminProfileController::class)->group(function () {
            Route::get('/profile', 'profile')->name('profile');
            Route::get('change-password', 'changePassword')->name('change_password');
            Route::put('change-password/{user}', 'updatePassword')->name('update.password');
        });

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        // // Route::resource('/apilogin', CAuthController::class);
        // Route::controller(CAuthController::class)->group(function () {
        //     Route::post('/login', 'login')->name('login');
        // });

        Route::controller(UserController::class)->group(function () {
            Route::get('/update_language/{user}/{language}', 'updateLanguage')->name('users.update_language');
            Route::get('/users/status/{id}/{status}', 'status')->name('users.status');
            Route::post('/users/download', 'export')->name('users.download');
        });
        Route::resource('/users', UserController::class);

        Route::controller(BattleController::class)->group(function () {
            Route::get('/battles/status/{id}/{status}', 'status')->name('battles.status');
        });
        Route::resource('/battles', BattleController::class);

        Route::controller(WinningController::class)->group(function () {
            Route::get('/winnings/status/{id}/{status}', 'status')->name('winnings.status');
        });
        Route::resource('/winnings', WinningController::class);

        Route::controller(GameController::class)->group(function () {
            Route::get('/games/status/{id}/{status}', 'status')->name('games.status');
            // Route::post('/games/store', 'store')->name('games.store');
        });
        Route::resource('/game', GameController::class);

        Route::controller(ResultController::class)->group(function () {
            Route::get('/results/status/{id}/{status}', 'status')->name('results.status');
            // Route::post('/games/store', 'store')->name('games.store');
            Route::get('/result/approve/{id}/{status}', 'approve')->name('result.approve');
        });
        Route::resource('/result', ResultController::class);

        Route::controller(GameResultController::class)->group(function () {
            Route::get('/gameresults/status/{id}/{status}', 'status')->name('gameresults.status');
            // Route::post('/games/store', 'store')->name('games.store');
        });
        Route::resource('/gameresult', GameResultController::class);


        Route::controller(WalletHistoryController::class)->group(function () {
            Route::get('/wallethistorys/status/{id}/{status}', 'status')->name('wallethistorys.status');
            // Route::post('/games/store', 'store')->name('games.store');
        });

        Route::resource('/wallethistory', WalletHistoryController::class);

        Route::controller(ExcelController::class)->group(function () {
            Route::get('/excels/status/{id}/{status}', 'status')->name('excels.status');
         
        });
        Route::resource('/excel', ExcelController::class);



        Route::controller(CustomerController::class)->group(function () {
            Route::get('/customers/status/{id}/{status}', 'status')->name('customers.status');
            Route::post('/customers/download', 'export')->name('customers.download');
            Route::get('/customers/download', 'export')->name('customers.getdownload');
        });
        Route::resource('/customers', CustomerController::class);

        Route::controller(ProductController::class)->group(function () {
            Route::get('/products/status/{id}/{status}', 'status')->name('products.status');
            Route::post('/products/download', 'export')->name('products.download');
            Route::get('/products/download', 'export')->name('products.getdownload');
            Route::post('/products/import', 'import')->name('products.import');
            Route::get('products/get-format-files', 'downloadImportFormatFile')->name('products.getfile');
            Route::delete('products/delete-images/{id}', 'deleteImage')->name('products.delete_image');
        });
        Route::resource('/products', ProductController::class);

        //Setting manager
        Route::controller(SettingController::class)->group(function () {
            Route::get('/settings/general', 'edit_general')->name('settings.edit_general');
            Route::post('/settings/general', 'update_general')->name('settings.update_general');
        });
    });
});

app/Http/Controllers/Admin/AdminProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UserRequest;
use App\Http\Requests\Admin\AdminChangePasswordRequest;
use App\Models\User;
use App\Services\HelperService;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Services\ManagerLanguageService;
use App\Services\UserService;

class AdminProfileController extends Controller
{
    protected $mls, $admin_profile_view, $change_password_view;

    public function __construct()
    {
        //mls is used for manage language content based on keys in messages.php
        $this->mls = new ManagerLanguageService('messages');
        //view files
        $this->admin_profile_view = 'admin.admin_profile.show';
        $this->change_password_view = 'admin.admin_profile.change_password';
    }

    /**
     * Update the language in User.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function updateLanguage(User $user, $language)
    {
        // dd($user, $language);
        $result = $user->update(['lang' => $language]);
        session()->put('locale', $language);
        if ($result) {
            return response()->json([
                'status' => 1,
                'message' => $this->mls->onlyNameLanguage('language_updated'),
                'status_name' => 'success'
            ]);
        } else {
            return response()->json([
                'status' => 0,
                'message' => $this->mls->onlyNameLanguage('language_not_updated'),
                'status_name' => 'error'
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  Auth user
     * @return \Illuminate\Http\Response
     */
    public function profile()
    {
        $page_title = $this->mls->onlyNameLanguage('profile');
        return view($this->admin_profile_view, compact('page_title'));
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function changePassword()
    {
        $data = Auth::user();
        $page_title = $this->mls->onlyNameLanguage('change_password');
        return view($this->change_password_view, compact('page_title', 'data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function updatePassword(AdminChangePasswordRequest $request, User $user)
    {

        $input = $request->except(['_token', '_method', 'proengsoft_jsvalidation']);

        $data = UserService::update_password($user, $request->password);

        return redirect()->back()->with('success', $this->mls->onlyNameLanguage('user_updated'));
    }
}

resources/views/admin/admin_profile/change_password.blade.php
@extends('admin.layouts.base')
@section('content')
    @include('admin.layouts.components.header',[
    'title'=> trans_choice('content.change_password', 1),
    'breadcrumbs'=> Breadcrumbs::render('admin.change-password')
    ])

    <!--begin::Post-->
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container">
            <!--begin::Navbar-->
            @include('admin.admin_profile.navbar')
            <!--end::Navbar-->
            <!-- begin::Basic Info  -->
            <!--begin::Careers - Apply-->
            <div class="card">
                <!--begin::Body-->
                <div class="card-body p-lg-17">
                    <!--begin::Hero-->
                    {{-- <div class="position-relative mb-17">
                        <!--begin::Overlay-->
                        <div class="overlay overlay-show">
                            <!--begin::Title-->
                            <h3 class="fs-2qx fw-bolder mb-3 m">
                                {{ trans_choice('content.change_password', 1) }}
                            </h3>
                            <!--end::Title-->
                        </div>
                        <!--end::Overlay-->
                    </div> --}}
                    <!--end::-->
                    <!--begin::Layout-->
                    <div class="d-flex flex-column flex-lg-row mb-17">
                        <!--begin::Content-->
                        <div class="flex-lg-row-fluid me-0 me-lg-20">

                            <!--begin::Form-->
                            {{ Form::model([],['url' => route('admin.update.password', ['user' => $auth_user->id]),'method' => 'PATCH','files' => true,'class' => 'form mb-15','role' => 'form','id' => 'adminForm']) }}
                            <input type="hidden" name="_method" value="PUT">
                            <input type="hidden" name="id" value="{{ $data->id }}">
                            <div class="row mb-5">
                                <!--begin::Col-->
                                <div class="col-md-8 fv-row">
                                    <!--begin::Label-->
                                    <label
                                        class="required fs-5 fw-bold mb-2">{{ __('content.old_password_title') }}</label>
                                    <!--end::Label-->
                                    <!--begin::Input-->
                                    {!! Form::password('old_password', ['class' => 'form-control', 'id' => 'old_password', 'placeholder' => __('placeholder.enter_old_password')]) !!}
                                    @if ($errors->has('old_password'))
                                        <span
                                            class="error invalid-feedback d-block">{{ $errors->first('old_password') }}</span>
                                    @endif
                                </div>
                                <!--end::Col-->
                            </div>
                            <div class="row mb-5">
                                <!--begin::Col-->
                                <div class="col-md-8 fv-row">
                                    <!--begin::Label-->
                                    <label class="required fs-5 fw-bold mb-2">{{ __('content.password_title') }}</label>
                                    <!--end::Label-->
                                    <!--begin::Input-->
                                    {!! Form::password('password', ['class' => 'form-control', 'id' => 'password', 'placeholder' => __('placeholder.enter_new_password')]) !!}
                                    @if ($errors->has('password'))
                                        <span
                                            class="error invalid-feedback d-block">{{ $errors->first('password') }}</span>
                                    @endif
                                </div>
                                <!--end::Col-->
                            </div>
                            <div class="row mb-5">
                                <div class="col-md-8 fv-row">
                                    <!--begin::Label-->
                                    <label
                                        class="required fs-5 fw-bold mb-2">{{ __('content.confirm_password_title') }}</label>
                                    <!--end::Label-->
                                    <!--begin::Input-->
                                    {!! Form::password('confirm_password', ['class' => 'form-control', 'id' => 'confirm_password', 'placeholder' => __('placeholder.enter_confirm_password')]) !!}
                                    @if ($errors->has('confirm_password'))
                                        <span
                                            class="error invalid-feedback d-block">{{ $errors->first('confirm_password') }}</span>
                                    @endif
                                </div>
                            </div>

                            <!--end::Input group-->
                            <!--begin::Submit-->
                            <button type="submit" class="btn btn-primary">{{ __('content.create_title') }}</button>
                            <!-- end::Submit -->
                            <!-- begin::Back  -->
                            <button type="button" class="btn btn-primary">
                                <a href="{{ route('admin.dashboard') }}"
                                    class="text-white">{{ __('content.back_title') }}</a>
                            </button>
                            <!-- end::Back  -->
                            {!! Form::close() !!}
                            <!--end::Form-->
                        </div>
                        <!--end::Content-->
                    </div>
                    <!--end::Layout-->
                </div>
                <!--end::Body-->
            </div>
            <!--end::Careers - Apply-->
            <!-- end:Basic Info  -->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Post-->
@endsection

@push('scripts')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js') }}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\Admin\AdminChangePasswordRequest', 'form') !!}
@endpush

resources/views/admin/admin_profile/show.blade.php
@extends('admin.layouts.base')
@section('content')
    @include('admin.layouts.components.header',[
    'title'=> trans_choice('header.profile_details', 1),
    'breadcrumbs'=> Breadcrumbs::render('admin.profile')
    ])

    <!--begin::Post-->
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container">
            <!--begin::Navbar-->
            @include('admin.admin_profile.navbar')
            <!--end::Navbar-->
            <!-- begin::Basic Info  -->
            <div class="card mb-5 mb-xl-10" id="kt_profile_details_view">
                {{-- <!--begin::Card header-->
                <div class="card-header cursor-pointer">
                    <!--begin::Card title-->
                    <div class="card-title m-0">
                        <h3 class="fw-bolder m-0">{{ __('content.profile_details') }}</h3>
                    </div>
                    <!--end::Card title-->
                </div>
                <!--begin::Card header--> --}}
                <!--begin::Card body-->
                <div class="card-body p-9">
                    <!--begin::Row-->
                    <div class="row mb-7">
                        <!--begin::Label-->
                        <label class="col-lg-4 fw-bold text-muted">{{ trans_choice('content.name_title', 1) }}</label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8">
                            <span class="fw-bolder fs-6 text-dark">{{ $auth_user->name }}</span>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Row-->
                    <!--begin::Input group-->
                    <div class="row mb-7">
                        <!--begin::Label-->
                        <label class="col-lg-4 fw-bold text-muted">{{ trans_choice('content.email_title', 1) }}</label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8 fv-row">
                            <span class="fw-bold fs-6">{{ $auth_user->email }}</span>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row mb-7">
                        <!--begin::Label-->
                        <label class="col-lg-4 fw-bold text-muted">{{ trans_choice('content.phone_title', 1) }}</label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8 d-flex align-items-center">
                            <span class="fw-bolder fs-6 me-2">{{ $auth_user->mobile_no }}</span>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row mb-7">
                        <!--begin::Label-->
                        <label class="col-lg-4 fw-bold text-muted">{{ trans_choice('content.role_title', 1) }}</label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8">
                            @if (!empty($auth_user->getRoleNames()))
                                @foreach ($auth_user->getRoleNames() as $v)
                                    <span class="fw-bolder fs-6 text-dark">{{ $v }}</span>
                                @endforeach
                            @endif
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->

                </div>
                <!--end::Card body-->
            </div>
            <!-- end:Basic Info  -->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Post-->
@endsection