routes/web.php
<?php

use App\Http\Controllers\Admin\AdminErrorPageController;
use App\Http\Controllers\Admin\GameController;
use App\Http\Controllers\Admin\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('admin.dashboard');
});
// Route::get('/admin', function () {
//     return redirect('/admin/dashboard');
// });
Auth::routes(['register' => false]);
// Route::get('/test', 'TestController@test');
// Route::controller(TestController::class)->group(function () {
//     //
// });
Route::get('/admin/test', 'TestController@test');



Route::group(['middleware' => ['optimizeImages'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', function () {
        return redirect()->route('admin.dashboard');
    });

    Route::controller(LoginController::class)->group(function () {
        Route::get('/login', 'showLoginForm')->name('login');
        Route::post('/login', 'login')->name('login');
        Route::post('/logout', 'logout')->name('logout');
    });
    Route::controller(AdminErrorPageController::class)->group(function () {
        Route::get('/404', 'pageNotFound')->name('notfound');
        Route::get('/500', 'serverError')->name('server_error');
    });
    Route::group(['middleware' => ['auth'], 'namespace' => 'Admin'], function () {

        Route::controller(DashboardController::class)->group(function () {
            Route::get('/test', 'test')->name('test');
            Route::get('/dashboard', 'index')->name('dashboard');
            Route::get('dashboard-counts', 'dashboardCountsData')->name('dashboard-counts');
        });

        Route::controller(AdminProfileController::class)->group(function () {
            Route::get('/profile', 'profile')->name('profile');
            Route::get('change-password', 'changePassword')->name('change_password');
            Route::put('change-password/{user}', 'updatePassword')->name('update.password');
        });

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        // // Route::resource('/apilogin', CAuthController::class);
        // Route::controller(CAuthController::class)->group(function () {
        //     Route::post('/login', 'login')->name('login');
        // });

        Route::controller(UserController::class)->group(function () {
            Route::get('/update_language/{user}/{language}', 'updateLanguage')->name('users.update_language');
            Route::get('/users/status/{id}/{status}', 'status')->name('users.status');
            Route::post('/users/download', 'export')->name('users.download');
        });
        Route::resource('/users', UserController::class);

        Route::controller(BattleController::class)->group(function () {
            Route::get('/battles/status/{id}/{status}', 'status')->name('battles.status');
        });
        Route::resource('/battles', BattleController::class);

        Route::controller(WinningController::class)->group(function () {
            Route::get('/winnings/status/{id}/{status}', 'status')->name('winnings.status');
        });
        Route::resource('/winnings', WinningController::class);

        Route::controller(GameController::class)->group(function () {
            Route::get('/games/status/{id}/{status}', 'status')->name('games.status');
            // Route::post('/games/store', 'store')->name('games.store');
        });
        Route::resource('/game', GameController::class);

        Route::controller(ResultController::class)->group(function () {
            Route::get('/results/status/{id}/{status}', 'status')->name('results.status');
            // Route::post('/games/store', 'store')->name('games.store');
            Route::get('/result/approve/{id}/{status}', 'approve')->name('result.approve');
        });
        Route::resource('/result', ResultController::class);

        Route::controller(GameResultController::class)->group(function () {
            Route::get('/gameresults/status/{id}/{status}', 'status')->name('gameresults.status');
            // Route::post('/games/store', 'store')->name('games.store');
        });
        Route::resource('/gameresult', GameResultController::class);


        Route::controller(WalletHistoryController::class)->group(function () {
            Route::get('/wallethistorys/status/{id}/{status}', 'status')->name('wallethistorys.status');
            // Route::post('/games/store', 'store')->name('games.store');
        });

        Route::resource('/wallethistory', WalletHistoryController::class);

        Route::controller(ExcelController::class)->group(function () {
            Route::get('/excels/status/{id}/{status}', 'status')->name('excels.status');
         
        });
        Route::resource('/excel', ExcelController::class);



        Route::controller(CustomerController::class)->group(function () {
            Route::get('/customers/status/{id}/{status}', 'status')->name('customers.status');
            Route::post('/customers/download', 'export')->name('customers.download');
            Route::get('/customers/download', 'export')->name('customers.getdownload');
        });
        Route::resource('/customers', CustomerController::class);

        Route::controller(ProductController::class)->group(function () {
            Route::get('/products/status/{id}/{status}', 'status')->name('products.status');
            Route::post('/products/download', 'export')->name('products.download');
            Route::get('/products/download', 'export')->name('products.getdownload');
            Route::post('/products/import', 'import')->name('products.import');
            Route::get('products/get-format-files', 'downloadImportFormatFile')->name('products.getfile');
            Route::delete('products/delete-images/{id}', 'deleteImage')->name('products.delete_image');
        });
        Route::resource('/products', ProductController::class);

        //Setting manager
        Route::controller(SettingController::class)->group(function () {
            Route::get('/settings/general', 'edit_general')->name('settings.edit_general');
            Route::post('/settings/general', 'update_general')->name('settings.update_general');
        });
    });
});

app/Http/Controllers/Admin/WalletHistoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\ExcelController;
use App\Http\Requests\Admin\GameRequest;
use App\Http\Requests\Admin\ApiGame_ResultRequest;
use App\Models\Wallet;
use App\Services\WalletService;
use App\Services\CustomerService;
use App\Services\ManagerLanguageService;
use App\Services\UserService;
use App\Services\UtilityService;
use Illuminate\Http\Request;

class WalletHistoryController extends Controller
{
    protected $mls, $change_password, $assign_role, $uploads_image_directory;
    protected $index_view, $create_view, $edit_view,$excel_view, $detail_view, $tabe_view, $product_history_view;
    protected $index_route_name, $create_route_name, $detail_route_name, $edit_route_name,$excel_route_name;
    protected $resultService, $utilityService, $customerService;

    public function __construct()
    {
        //Permissions
        // $this->middleware('permission:battle-list|battle-create|battle-edit|battle-delete', ['only' => ['index', 'store']]);
        // $this->middleware('permission:battle-create', ['only' => ['create', 'store']]);
        // $this->middleware('permission:battle-edit', ['only' => ['edit', 'update', 'status']]);
        // $this->middleware('permission:battle-delete', ['only' => ['destroy']]);

        //Data
        $this->uploads_image_directory = 'files/game';
        //route
        $this->index_route_name = 'admin.wallethistory.index';
        
        $this->create_route_name = 'admin.wallethistory.create';
        
        $this->detail_route_name = 'admin.wallethistory.show';
        $this->edit_route_name = 'admin.wallethistory.edit';
        // $this->excel_form_route_name = 'admin.game.excel_form';

        //view files
        $this->index_view = 'admin.wallethistory.index';
        $this->create_view = 'admin.wallethistory.create';
        
        $this->detail_view = 'admin.wallethistory.details';
        $this->tabe_view = 'admin.wallethistory.profile';
        $this->edit_view = 'admin.wallethistory.edit';
        // $this->excel_form_view = 'admin.game.excel_form';
        
        $this->product_history_view = 'admin.wallethistory.product_history';
        $this->change_password = 'admin.admin_profile.change_password';

        //service files
        $this->walletService = new WalletService();
        // $this->customerService = new CustomerService();
        // $this->utilityService = new UtilityService();

        //mls is used for manage language content based on keys in messages.php
        $this->mls = new ManagerLanguageService('messages');
    }

    public function index(Request $request)
    {
        if ($request->ajax()) {
            $items = $this->walletService->datatable();
            // print_r($items);
            // die;
            // $items = $this->battleService->search($request, $items);
            return datatables()->eloquent($items)->toJson();
        } else {
            return view($this->index_view);
        }
    }

    public function create()
    {
        return view($this->create_view);
    }
    



    public function show(Wallet $game)
    {
            
        return view($this->detail_view, compact('game_result'));
    }

    
    // public function excel_form(Game $game)
    // {
    //     return view($this->excel_view, compact('game'));
    // }

   

    

    public function status($id, $status)
    {
        $status = ($status == 1) ? 0 : 1;
        $result =  $this->resultService->updateById(['is_active' => $status], $id);
        if ($result) {
            return response()->json([
                'status' => 1,
                'message' => $this->mls->messageLanguage('updated', 'status', 1),
                'status_name' => 'success'
            ]);
        } else {
            return response()->json([
                'status' => 0,
                'message' => $this->mls->messageLanguage('not_updated', 'status', 1),
                'status_name' => 'error'
            ]);
        }
    }
}

resources/views/admin/wallethistory/details.blade.php
@extends('admin.layouts.base')
@section('content')
    @include('admin.layouts.components.header', [
        'title' => __('messages.edit', ['name' => trans_choice('content.wallethistory', 1)]),
        'breadcrumbs' => Breadcrumbs::render('admin.wallethistory.show'),
    ])

    <!--begin::Post-->
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container">

            <!--begin::Basic info-->
            <div class="card mb-5 mb-xl-10">
                <!--begin::Content-->
                <div id="kt_account_profile_details">

                    <!--begin::Card body-->
                    <div class="card-body border-top p-9">

                        <!--begin::Input group-->
                        <div class="row mb-5">
                            <div class="col-md-4 fv-row">
                                <div class="fs-5 fw-bold mb-2">Name
                                </div>
                                <div class="fs-5 text-gray-600">{{ $game->name }}</div>
                            </div>
                            <div class="col-md-4 fv-row">
                                <div class="fs-5 fw-bold mb-2">No Player
                                </div>
                                <div class="fs-5 text-gray-600">{{ $game->no_player }}</div>
                            </div>
                            <div class="col-md-4 fv-row">
                                <div class="fs-5 fw-bold mb-2">Entry Amount</div>
                                <div class="fs-5 text-gray-600">{{ $game->entry_amount }}</div>
                            </div>
                        </div>
                        <!--end::Input group-->
                        <!--begin::Input group-->
                        <div class="row mb-5">
                            <div class="col-md-4 fv-row">
                                <div class="fs-5 fw-bold mb-2">Win Amount
                                </div>
                                <div class="fs-5 text-gray-600">{{ $game->win_amount }}</div>
                            </div>
                            <!-- <div class="col-md-4 fv-row">
                                <div class="fs-5 fw-bold mb-2">{{ trans_choice('content.start_time_title', 1) }}</div>
                                <div class="fs-5 text-gray-600">{{ $battle->start_time }}</div>
                            </div> -->
                            <div class="col-md-4 fv-row">
                                <div class="fs-5 fw-bold mb-2">{{ trans_choice('content.status_title', 1) }}</div>
                                @if ($battle->status == 1)
                                    <div class="badge badge-light-success fw-bolder">
                                        {{ trans_choice('content.open_title', 1) }} </div>
                                @else
                                    <div class="badge badge-light-primary fw-bolder">
                                        {{ trans_choice('content.running_title', 1) }} </div>
                                @endif

                            </div>
                        </div>
                        <!--end::Input group-->

                    </div>
                    <!--end::Card body-->
                    <!--begin::Actions-->
                    <div
                        class="card-footer d-flex justify-content-end py-6 px-9">
                        <button type="button" class="btn btn-primary">
                            <a href="{{ route('admin.battles.index') }}"
                                class="text-white">{{ __('content.back_title') }}</a>
                        </button>
                    </div>
                    <!--end::Actions-->

                </div>
                <!--end::Content-->
            </div>
            <!--end::Basic info-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Post-->
@endsection

resources/views/admin/wallethistory/index.blade.php
@extends('admin.layouts.base')

{{-- @section('admin_filter_form')
    {!! Form::open(['route' => 'admin.wallethistorys.download', 'method' => 'POST', 'id' => 'filter_data', 'class' => 'form mb-15']) !!}
    <!--begin::Card body-->
    
    <div class="card-body">
        <!--begin::Input group-->
        <div class="row mb-6">
            <!--begin::Label-->
            <label
                class="col-lg-4 col-form-label required fw-bold fs-6">{{ trans_choice('content.wallethistorys.name', 1) }}</label>
            <!--end::Label-->
            <!--begin::Col-->
            <div class="col-lg-8 fv-row">
                <!-- {!! Form::text('name', null, ['placeholder' => __('content.battles.name'), 'value' => 'Max', 'class' => 'form-control form-control-lg form-control-solid mb-3 mb-lg-0 search_input']) !!} -->
            <input type="text" name="wallethistory_name" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0 search_input">
            </div>
            <!--end::Col-->

        </div>
        <!--end::Input group-->

        <!--begin::Input group-->
        <div class="row mb-6">
            <!--begin::Label-->
            <label class="col-lg-4 col-form-label fw-bold fs-6">
                <span class="required">{{ trans_choice('content.wallethistorys.id', 1) }}</span>
            </label>
            <!--end::Label-->
            <!--begin::Col-->
            <div class="col-lg-8 fv-row">
                <!-- {!! Form::text('battle_id', null, ['placeholder' => __('placeholder.battle_id'), 'class' => 'form-control form-control-lg form-control-solid only_number search_input']) !!} -->
                <input type="text" name="result_id" class="form-control form-control-lg form-control-solid only_number search_input" placeholder="result id">
            </div>
            <!--end::Col-->
        </div>

        
        <!--end::Input group-->

        <!--begin::Input group-->
        <div class="row mb-6">
            <!--begin::Label-->
            <label class="col-lg-4 col-form-label fw-bold fs-6">{{ trans_choice('content.status_title', 1) }}</label>
            <!--end::Label-->
            <!--begin::Input-->
            <div class="col-lg-8 fv-row">
                <select class="form-control form-control-lg form-control-solid search_input" data-control="select2"
                    name="status">
                    <option value="">{{ trans_choice('content.please_select', 1) }}</option>
                    <option value="1">{{ trans_choice('content.active_title', 1) }}</option>
                    <option value="0">{{ trans_choice('content.inactive_title', 1) }}</option>
                </select>
            </div>
            <!--end::Input-->
        </div>
        <!--end::Input group-->
        <!--end::Input group-->
    </div>
    <!--end::Card body-->

    <!--begin::Actions-->
    <div class="d-flex justify-content-end">
        @include('admin.layouts.components.buttons.white_btn', [
            'type' => 'reset',
            'id' => 'searchReset',
            'attr' => 'data-kt-menu-dismiss="true"',
            'title' => trans_choice('content.reset', 1),
            'class' => 'btn-active-light-primary',
        ])
        @include('admin.layouts.components.buttons.primary_btn', [
            'id' => 'extraSearch',
            'attr' => 'data-kt-menu-dismiss="true"',
            'title' => __('content.search_title'),
        ])
        @include('admin.layouts.components.buttons.exportbtn')
    </div>
    <!--end::Actions-->
    {!! Form::close() !!}
@endsection --}}

@section('content')
    @include('admin.layouts.components.header', [
        'title' => __('messages.list', [
            'name' => trans_choice('content.result', 2),
        ]),
        'breadcrumbs' => Breadcrumbs::render('admin.wallethistory.index'),
        
        // 'export' => [
        //     'status' => true,
        //     'route' => route('admin.wallethistorys.getdownload'),
        // ],
    ])
    @include('admin.layouts.components.datatable_header', [
        'data' => [
            ['classname' => '', 'title' => trans_choice('content.id_title', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.wallet_amount', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.user_id', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.transaction_id', 1)],
            ['classname' => 'min-w-125px', 'title' => trans_choice('content.status', 1)],
            
             
            
            
        ],
    ])
@endsection

@push('scripts')
    <script>
        var oTable;
        $(document).ready(function() {
            oTable = $('#kt_table_1').DataTable({
                responsive: true,
                searchDelay: 500,
                processing: true,
                serverSide: true,
                order: [
                    [0, 'desc']
                ],
                oLanguage: {
                    sLengthMenu: "Show _MENU_",
                },
                createdRow: function(row, data, dataIndex) {
                    // Set the data-status attribute, and add a class
                    $(row).attr('role', 'row');
                    $(row).find("td").last().addClass('text-danger');
                },
                ajax: {
                    "url": "{{ route('admin.wallethistory.index') }}",
                },
             
                columns: [{
                        data: 'id',
                        name: 'id',
                        render: function(data, type, row, meta) {
                            return data;
                            // return "#" + serialNumberShow(meta);
                        }
                    },

                    {
                        data: 'wallet_amount',
                        name: 'wallet_amount',
                        render: function(data, type, row, meta) {
                            var show_url = `{{ url('/') }}/admin/wallethistory/` + row['id'] +
                                `?tab=details`;
                            return ` <a href="${show_url}">
                                        <div class="font-medium whitespace-no-wrap">${data}</div>
                                    </a>`;
                        }
                    },
                    
                    {
                        data: 'user_id',
                        name: 'user_id',
                        render: function(data, type, row, meta) {
                            return `<div class="font-medium whitespace-no-wrap">${data}</div>`;
                        }
                    },
                   
                   
                    {
                        data: 'transaction_id',
                        name: 'transaction_id',
                        render: function(data, type, row, meta) {
                            // return `<div class="font-medium whitespace-no-wrap">getDateTimeByFormat(${data})</div>`;
                            return `<div class="font-medium whitespace-no-wrap">${data}</div>`;
                        }
                    },
                 
                    {
                        data: 'status',
                        name: 'status',
                        render: function(data, type, row, meta) {
                           var game_status='';
                            if(data==0){
                                game_status="Credit"
                            }else if(data==1){
                                game_status="Debit"
                            }
                            // return `<div class="font-medium whitespace-no-wrap">getDateTimeByFormat(${data})</div>`;
                            return `<div class="font-medium whitespace-no-wrap">${game_status}</div>`;
                        }
                    },
                                      
                    // {
                    //     data: 'id',
                    //     name: 'id',
                        
                    //     render: function(data, type, row, meta) {

                    //         var edit_url = `{{ url('/') }}/admin/wallethistory/` + row['id'] +
                    //             `/edit/?tab=edit`;
                    //         var show_url = `{{ url('/') }}/admin/wallethistory/` + row['id'] +
                    //             `?tab=details`;
                            

                    //         var edit_data = actionEditButton(edit_url, row['id']);
                    //         var show_data = actionShowButton(show_url);
                            
                    //         var del_data = actionDeleteButton(row['id']);
                    //         return `<div class="flex justify-left items-center"> ${show_data}  ${edit_data} ${del_data} </div>`;

                            

                    //     }
                    // },
                ],
            });
            // //start: datatables common js file for changing
            // oTable.columns().iterator('column', function(ctx, idx) {
            //     $(oTable.column(idx).header()).append('<span class="sort-icon"/>');
            // });
            //end: datatables common js file for changing
        });

        $(document).on('click', '.clsdelete', function() {
            var id = $(this).attr('data-id');
            var e = $(this).parent().parent();
            var url = `{{ url('/') }}/admin/wallethistory/` + id;
            tableDeleteRow(url, oTable);
        });

        $(document).on('click', '.clsstatus', function() {
            var id = $(this).attr('data-id');
            var status = $(this).attr('data-status');
            var url = `{{ url('/') }}/admin/result/status/` + id + `/` + status;
            tableChnageStatus(url, oTable);
        });
    </script>

    <script>
        $('#extraSearch').on('click', function() {
            //extraSearch is id of search button....
            oTable.draw();
        });

        $(document).on('click', '#searchReset', function(e) {
            $('#filter_data').trigger("reset");
            e.preventDefault();
            oTable.draw();
        });

        $(document).on('click', '.drawerReset', function(e) {
            $('#filter_data').trigger("reset");
            e.preventDefault();
            oTable.draw();
        });

        $(document).ready(function() {
            $('#filter_data').trigger("reset");
            oTable.draw();
        });

        $(document).on('click', '#search_filter_excel_download', function(e) {
            var export_type = $(this).attr('data-type');
            console.log(export_type);
            $('#export_type').val(export_type);
            $('#filter_data').submit();
        });
    </script>
@endpush